// Declarative field config for the Edit Case form — same spirit as
// components/calculator/inputFieldsConfig.js. `topLevel: true` fields read/write
// the case's existing top-level keys directly (so edits are visible everywhere
// that already reads those keys) instead of being duplicated into `caseDetails`.

export const CASE_CATEGORY_OPTIONS = [
  "Civil",
  "Criminal",
  "Family",
  "Consumer",
  "Arbitration",
  "Labour & Employment",
  "Company / NCLT",
  "Tax",
  "Writ Petition",
  "Property",
];

const STAGE_OPTIONS = [
  "Institution",
  "Notice Stage",
  "Admission",
  "Written Statement",
  "Evidence",
  "Cross Examination",
  "Arguments",
  "Final Hearing",
  "Reply",
  "Judgment",
];

export const BASE_FIELDS = [
  { name: "caseNumber", label: "Case Number", required: true, topLevel: true, topLevelKey: "number" },
  { name: "caseTitle", label: "Case Title / Case Name", required: true, topLevel: true, topLevelKey: "parties" },
  { name: "courtName", label: "Court Name", required: true, topLevel: true, topLevelKey: "court" },
  { name: "courtComplex", label: "Court Complex" },
  { name: "courtRoomNumber", label: "Court Room Number", topLevel: true, topLevelKey: "room" },
  { name: "bench", label: "Bench", type: "select", options: ["", "Single Bench", "Division Bench", "Full Bench"] },
  { name: "judgeName", label: "Presiding Judge Name", required: true, topLevel: true, topLevelKey: "judge" },
  { name: "judgeDesignation", label: "Presiding Judge Designation" },
  { name: "currentStage", label: "Current Stage of Proceedings", type: "select", options: STAGE_OPTIONS, topLevel: true, topLevelKey: "stage" },
  { name: "caseCategory", label: "Case Category", type: "select", options: CASE_CATEGORY_OPTIONS, required: true },
  { name: "caseType", label: "Case Type" },
  { name: "practiceArea", label: "Practice Area" },
  { name: "jurisdiction", label: "Jurisdiction", type: "select", options: ["Original", "Appellate", "Revisional", "Writ", "Execution"] },
  { name: "filingNumber", label: "Filing Number" },
  { name: "registrationNumber", label: "Registration Number" },
  { name: "cnrNumber", label: "CNR Number" },
  { name: "dateOfInstitution", label: "Date of Institution", type: "date" },
  { name: "dateOfRegistration", label: "Date of Registration", type: "date" },
  { name: "caseStatus", label: "Case Status", type: "select", options: ["Active", "Stayed", "Closed", "Disposed"], required: true },
  { name: "priorityLevel", label: "Priority Level", type: "select", options: ["High", "Medium", "Low"], required: true },
  { name: "assignedAdvocate", label: "Assigned Advocate", required: true },
  { name: "opposingCounsel", label: "Opposing Counsel" },
  { name: "tags", label: "Tags / Labels", hint: "Comma-separated, e.g. Urgent, High Value" },
];

// Category-specific groups, keyed by the exact CASE_CATEGORY_OPTIONS value.
// Only the group matching the form's current Case Category is rendered/validated.
export const CATEGORY_FIELD_GROUPS = {
  Criminal: [
    { name: "firNumber", label: "FIR Number", required: true },
    { name: "firDate", label: "FIR Date", type: "date" },
    { name: "policeStation", label: "Police Station" },
    { name: "crimeNumber", label: "Crime Number" },
    { name: "sections", label: "Sections of Law (IPC/BNS & Special Acts)", full: true },
    { name: "investigatingOfficer", label: "Investigating Officer" },
    { name: "chargeSheetNumber", label: "Charge Sheet Number" },
    { name: "chargeSheetDate", label: "Charge Sheet Date", type: "date" },
    { name: "arrestDate", label: "Arrest Date", type: "date" },
    { name: "bailStatus", label: "Bail Status", type: "select", options: ["Not Applied", "Applied", "Granted", "Rejected"] },
    { name: "bailApplicationNumber", label: "Bail Application Number" },
    { name: "custodyStatus", label: "Custody Status", type: "select", options: ["Judicial Custody", "Police Custody", "On Bail", "N/A"] },
    { name: "complainant", label: "Complainant" },
    { name: "accusedDetails", label: "Accused Details", full: true, type: "textarea", rows: 3 },
    { name: "prosecutor", label: "Prosecutor" },
    { name: "caseDiaryNumber", label: "Case Diary Number" },
  ],
  Civil: [
    { name: "suitValuation", label: "Suit Valuation (₹)", required: true },
    { name: "reliefClaimed", label: "Relief Claimed", full: true },
    { name: "natureOfSuit", label: "Nature of Suit" },
    { name: "causeOfActionDate", label: "Cause of Action Date", type: "date" },
    { name: "propertyDetails", label: "Property Details", full: true, type: "textarea", rows: 3 },
    { name: "surveyNumber", label: "Survey Number" },
    { name: "ctsNumber", label: "CTS Number" },
    { name: "scheduleProperty", label: "Schedule Property", full: true, type: "textarea", rows: 3 },
    { name: "limitationDate", label: "Limitation Date", type: "date" },
    { name: "courtFeePaid", label: "Court Fee Paid (₹)" },
    { name: "valuationMethod", label: "Valuation Method", type: "select", options: ["Ad Valorem", "Fixed Court Fee", "Schedule Fee", "Percentage Based"] },
  ],
  Family: [
    { name: "marriageDate", label: "Marriage Date", type: "date", required: true },
    { name: "separationDate", label: "Separation Date", type: "date" },
    { name: "childrenDetails", label: "Children Details", full: true, type: "textarea", rows: 3 },
    { name: "maintenanceClaimed", label: "Maintenance Claimed (₹)" },
    { name: "custodyDetails", label: "Custody Details", full: true, type: "textarea", rows: 3 },
    { name: "domesticViolenceProceedings", label: "Domestic Violence Proceedings", type: "select", options: ["No", "Yes"] },
    { name: "divorcePetitionType", label: "Divorce Petition Type", type: "select", options: ["", "Mutual Consent", "Contested"] },
  ],
  Consumer: [
    { name: "complaintValue", label: "Complaint Value (₹)", required: true },
    { name: "productOrService", label: "Product / Service" },
    { name: "consumerCommission", label: "Consumer Commission", type: "select", options: ["District", "State", "National"] },
    { name: "oppositeParty", label: "Opposite Party" },
    { name: "compensationClaimed", label: "Compensation Claimed (₹)" },
    { name: "deficiencyType", label: "Deficiency Type" },
  ],
  Arbitration: [
    { name: "agreementDate", label: "Arbitration Agreement Date", type: "date" },
    { name: "clauseReference", label: "Arbitration Clause Reference", required: true, full: true },
    { name: "tribunalType", label: "Sole / Three Member Tribunal", type: "select", options: ["Sole Arbitrator", "Three-Member Tribunal"] },
    { name: "seat", label: "Seat of Arbitration" },
    { name: "venue", label: "Venue" },
    { name: "institution", label: "Institution" },
    { name: "arbitrators", label: "Arbitrator(s)", full: true },
  ],
  "Labour & Employment": [
    { name: "employer", label: "Employer", required: true },
    { name: "employee", label: "Employee", required: true },
    { name: "employmentPeriod", label: "Employment Period" },
    { name: "designation", label: "Designation" },
    { name: "labourAuthority", label: "Labour Authority" },
    { name: "industrialDisputeNumber", label: "Industrial Dispute Number" },
  ],
  "Company / NCLT": [
    { name: "cin", label: "CIN" },
    { name: "companyName", label: "Company Name", required: true },
    { name: "petitionNumber", label: "Petition Number" },
    { name: "insolvencyProfessional", label: "Insolvency Professional" },
    { name: "resolutionProfessional", label: "Resolution Professional" },
    { name: "corporateDebtor", label: "Corporate Debtor" },
    { name: "creditorType", label: "Operational / Corporate Creditor", type: "select", options: ["Operational Creditor", "Financial/Corporate Creditor"] },
  ],
  Tax: [
    { name: "assessmentYear", label: "Assessment Year", required: true },
    { name: "taxAuthority", label: "Tax Authority" },
    { name: "gstOrPan", label: "GST/PAN" },
    { name: "appealNumber", label: "Appeal Number" },
    { name: "taxDemand", label: "Tax Demand (₹)" },
    { name: "assessmentOrderDate", label: "Assessment Order Date", type: "date" },
  ],
  "Writ Petition": [
    { name: "governmentDepartment", label: "Government Department" },
    { name: "constitutionalArticles", label: "Constitutional Articles Invoked", required: true },
    { name: "publicAuthority", label: "Public Authority" },
    { name: "reliefSought", label: "Relief Sought", full: true, type: "textarea", rows: 3 },
  ],
  Property: [
    { name: "propertyAddress", label: "Property Address", required: true, full: true, type: "textarea", rows: 2 },
    { name: "surveyNumber", label: "Survey Number" },
    { name: "ctsNumber", label: "CTS Number" },
    { name: "registrationNumber", label: "Registration Number" },
    { name: "registrationDate", label: "Registration Date", type: "date" },
    { name: "marketValue", label: "Market Value (₹)" },
    { name: "stampDutyDetails", label: "Stamp Duty Details", full: true, type: "textarea", rows: 2 },
  ],
};

// Maps a Case Category value to the caseDetails key its group is stored under.
export const CATEGORY_STORAGE_KEY = {
  Criminal: "criminal",
  Civil: "civil",
  Family: "family",
  Consumer: "consumer",
  Arbitration: "arbitration",
  "Labour & Employment": "labour",
  "Company / NCLT": "company",
  Tax: "tax",
  "Writ Petition": "writ",
  Property: "property",
};
