"use client";

import { formatDateTime, formatInr } from "./format";

function Field({ label, value }) {
  return (
    <div className="field">
      <label>{label}</label>
      <div className="field-value">{value === "" || value === null || value === undefined ? "—" : String(value)}</div>
    </div>
  );
}

const COST_ROWS = [
  { key: "courtFee", label: "Court Fee" },
  { key: "filingCharges", label: "Filing & Process Fee" },
  { key: "documentation", label: "Documentation & Copying" },
  { key: "miscExpenses", label: "Miscellaneous Disbursements" },
  { key: "administrativeCharges", label: "Administrative Charges" },
  { key: "governmentFees", label: "Government Fees" },
  { key: "courtProcessExpenses", label: "Court Process Expenses" },
  { key: "incidentalExpenses", label: "Incidental Expenses" },
  { key: "professionalExpenses", label: "Professional Expenses" },
  { key: "gstAmount", label: "GST" },
];

export default function ViewCalculationModal({ entry, onClose }) {
  if (!entry) return null;
  const snapshot = entry.snapshot;

  return (
    <div className="case-modal-backdrop show" onClick={(e) => e.target === e.currentTarget && onClose()}>
      <div className="case-modal wide">
        <div className="modal-head">
          <div>
            <p className="eyebrow">HISTORICAL CALCULATION · READ-ONLY</p>
            <h2>{entry.event}</h2>
          </div>
          <button type="button" className="modal-close" onClick={onClose}>
            ×
          </button>
        </div>
        <div className="modal-body">
          {!snapshot ? (
            <div className="empty-inline">No snapshot was saved with this audit entry.</div>
          ) : (
            <>
              <div className="field-group">
                <h4>1. Estimate Information</h4>
                <div className="field-row">
                  <Field label="Estimate ID" value={snapshot.estimateId} />
                  <Field label="Date & Time Generated" value={formatDateTime(entry.timestamp)} />
                  <Field label="Generated By" value={entry.user} />
                  <Field label="State" value={snapshot.state} />
                  <Field label="Court" value={snapshot.court} />
                  <Field label="Rules Version Applied" value={snapshot.rulesVersion} />
                  <Field label="Last Modified" value={snapshot.lastModified ? formatDateTime(snapshot.lastModified) : "—"} />
                </div>
              </div>

              <div className="field-group">
                <h4>2. Selected Case</h4>
                {snapshot.linkedCase ? (
                  <div className="field-row">
                    <Field label="Case Title" value={snapshot.linkedCase.title} />
                    <Field label="Case Number" value={snapshot.linkedCase.number} />
                    <Field label="Case Type" value={snapshot.linkedCase.type} />
                    <Field label="Court" value={snapshot.linkedCase.court} />
                    <Field label="State" value={snapshot.state} />
                  </div>
                ) : (
                  <div className="empty-inline">No case was linked at the time of this calculation.</div>
                )}
              </div>

              <div className="field-group">
                <h4>3. Input Details</h4>
                <div className="field-row">
                  <Field label="Nature of Proceeding" value={snapshot.inputs.natureOfProceeding} />
                  <Field label="Relief Claimed" value={formatInr(snapshot.inputs.reliefClaimed)} />
                  <Field label="Valuation Method" value={snapshot.inputs.valuationMethod} />
                  <Field label="Suit Valuation" value={formatInr(snapshot.inputs.suitValuation)} />
                  <Field label="State" value={snapshot.inputs.state} />
                  <Field label="District" value={snapshot.inputs.district} />
                  <Field label="Court" value={snapshot.inputs.court} />
                  <Field label="Court Level" value={snapshot.inputs.courtLevel} />
                  <Field label="Jurisdiction" value={snapshot.inputs.jurisdiction} />
                  <Field label="Plaintiffs" value={snapshot.inputs.plaintiffs} />
                  <Field label="Defendants" value={snapshot.inputs.defendants} />
                  <Field label="Reliefs" value={snapshot.inputs.reliefs} />
                  <Field label="Applications" value={snapshot.inputs.applications} />
                  <Field label="Annexures" value={snapshot.inputs.annexures} />
                  <Field label="Pages" value={snapshot.inputs.pages} />
                  <Field label="Certified Copies" value={snapshot.inputs.certifiedCopies} />
                </div>
              </div>

              <div className="field-group">
                <h4>4. Estimated Total Litigation Cost</h4>
                {COST_ROWS.map((row) => (
                  <div className="cost-row" key={row.key}>
                    <span>{row.label}</span>
                    <b>{formatInr(snapshot.totals[row.key])}</b>
                  </div>
                ))}
                <div className="cost-row">
                  <span>
                    <strong>Grand Total</strong>
                  </span>
                  <b>{formatInr(snapshot.totals.grandTotal)}</b>
                </div>
              </div>

              <div className="field-group">
                <h4>5. Statutory References</h4>
                {snapshot.statutoryReferences.length ? (
                  snapshot.statutoryReferences.map((ref) => (
                    <div className="explanation-item" key={ref.id}>
                      <div className="explanation-item-head">
                        <b>{ref.act}</b>
                        <span>{ref.sections}</span>
                      </div>
                      <p>{ref.fullText}</p>
                      <small>Rules Version at time of calculation: {snapshot.rulesVersion}</small>
                    </div>
                  ))
                ) : (
                  <div className="empty-inline">No statutory references were recorded for this calculation.</div>
                )}
              </div>
            </>
          )}
        </div>
        <div className="modal-foot">
          <button type="button" className="btn btn-outline" onClick={onClose}>
            Close
          </button>
        </div>
      </div>
    </div>
  );
}
